### ISSUE TITLE
name already exists

### ISSUE THREAD

**Issue by Yassy-Ubuntu** [GangCaoLab/sciDLO#1]
I meet this problem:

~~~
(dlo-hic-tools) msbb@msbb-OptiPlex-7000:~/Yasmine/sciDLO/test_data$ dlohic extract_fragments ../../reference/hg19.fa  -r MseI:T^tAA  MseI.hdf5
dlo_hic.tools.helper.extract_fragments INFO    @ 12/19/23 14:25:44: Extract fragments MseI:T^tAA from ../../reference/hg19.fa
dlo_hic.tools.helper.extract_fragments INFO    @ 12/19/23 14:25:44: 1 workers spawned for extract restriction sites
Process Process-2:
Traceback (most recent call last):
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/site-packages/dlo_hic-0.3.9-py3.6-linux-x86_64.egg/dlo_hic/tools/helper/extract_fragments.py", line 86, in outputer
    f.create_dataset("chromosomes/"+chr_, data=np.array(out_chunk, dtype=np.int))
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/site-packages/h5py/_hl/group.py", line 139, in create_dataset
    self[name] = dset
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/site-packages/h5py/_hl/group.py", line 373, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
OSError: Unable to create link (name already exists)
^CProcess Process-1:

Aborted!
Traceback (most recent call last):
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/site-packages/dlo_hic-0.3.9-py3.6-linux-x86_64.egg/dlo_hic/tools/helper/extract_fragments.py", line 52, in worker
    output_queue.put( (chr_, '-', out_chunk) )
  File "/home/msbb/anaconda3/envs/dlo-hic-tools/lib/python3.6/multiprocessing/queues.py", line 82, in put
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt
~~~

I have no idea how to deal with this error! THX..

**Comment by Nanguage** [comment]
It seems that clearing the cache is needed. Is there already a file with the same name as the result file in your working directory (or nextflow's working directory)?
